language: node_js
node_js:
  - "stable"
# cache:
#   directories:
#   - node_modules
before_script:
  - npm install -g gatsby-cli
script:
  - echo $BACKEND_BASE_URL
  - gatsby build --prefix-paths
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master